Tweaked configure to silently ignore commandline options it doesn't know about.  No use in quitting if the option wouldn't have had any effect anyway.
git-svn-id: svn://svn.code.sf.net/p/stella/code/trunk@603 8b62c5a3-ac7e-4cc8-8f21-d9a121418aba

diff --git a/stella/configure b/stella/configure
--- a/stella/configure
+++ b/stella/configure
@@ -316,11 +316,11 @@ for ac_option in $@; do
       --mandir=*)
         _mandir=`echo $ac_option | cut -d '=' -f 2`
         ;;
-      *)
-        echo "error: unrecognised option: $ac_option
-Try \`$0 --help' for more information." >&2
-        exit 1
-        ;;
+#      *)
+#        echo "error: unrecognised option: $ac_option
+#Try \`$0 --help' for more information." >&2
+#        exit 1
+#        ;;
     esac;
 done;
 
